name = "trend-radar-mvp"
main = "src/index.js"
compatibility_date = "2026-10-02"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "trend-radar-db"
database_id = "286bcdfd-a4f3-4e34-b85a-9f1271aacfbc"
