name = "trend-radar"
main = "src/index.js"
compatibility_date = "2026-10-02"

[triggers]
crons = ["*/30 * * * *"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "trend-radar-core"
database_id = "39ebabd1-35b5-4308-af67-ad92b0baed01"
