const JSON_HEADERS = {"content-type":"application/json; charset=UTF-8","cache-control":"no-store"};
const SOURCE_URLS = {googleTrends:"https://trends.google.com/trending/rss?geo=US",hackerNews:"https://hacker-news.firebaseio.com/v0/beststories.json"};
function decodeEntities(s){return String(s||"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
function xmlTag(block,tag){const re=new RegExp("<(?:[\\w-]+:)?"+tag+"[^>]*>([\\s\\S]*?)<\\/(?:[\\w-]+:)?"+tag+">","i");const m=block.match(re);return m?decodeEntities(m[1].trim()):"";}
function parseTraffic(s){const m=String(s||"").replace(/,/g,"").match(/([0-9.]+)([KkMmBb])?/);if(!m)return 0;const n=Number(m[1]);return m[2]?(["K","k"].includes(m[2])?n*1e3:["M","m"].includes(m[2])?n*1e6:n*1e9):n;}
function now(){return new Date().toISOString();}
function score(x){let s=0;if(x.source==="google_trends")s=Math.min(60,x.signal_value/20000);if(x.source==="hacker_news")s=Math.min(35,x.signal_value/20);const age=Math.max(0,(Date.now()-new Date(x.published_at||now()).getTime())/3600000);return Math.round(Math.min(100,s+Math.max(0,25-age))*100)/100;}
async function getText(url){const r=await fetch(url,{headers:{"user-agent":"trend-radar-mvp/1.0"}});if(!r.ok)throw new Error("HTTP "+r.status+" from "+url);return r.text();}
async function getJson(url){const r=await fetch(url,{headers:{"user-agent":"trend-radar-mvp/1.0"}});if(!r.ok)throw new Error("HTTP "+r.status+" from "+url);return r.json();}
async function readGoogleTrends(){const xml=await getText(SOURCE_URLS.googleTrends),out=[];for(const block of xml.split(/<item>/i).slice(1)){const b=block.split(/<\/item>/i)[0],title=xmlTag(b,"title");if(!title)continue;const link=xmlTag(b,"link"),pub=xmlTag(b,"pubDate"),traffic=xmlTag(b,"approx_traffic");out.push({source:"google_trends",external_id:title.toLowerCase(),title,url:link||null,published_at:pub?new Date(pub).toISOString():now(),signal_value:parseTraffic(traffic),category:"web"});}return out.slice(0,100);}
async function readHackerNews(){const ids=(await getJson(SOURCE_URLS.hackerNews)).slice(0,10),out=[];for(const id of ids){try{const item=await getJson("https://hacker-news.firebaseio.com/v0/item/"+id+".json");if(item&&item.type==="story"&&item.title)out.push({source:"hacker_news",external_id:String(id),title:item.title,url:item.url||("https://news.ycombinator.com/item?id="+id),published_at:new Date(Number(item.time||0)*1000).toISOString(),signal_value:Number(item.score||0),category:"technology"});}catch(_){}}return out;}
async function upsert(env,x){const t=now(),s=score(x);await env.DB.prepare("INSERT INTO signals(source,external_id,title,url,published_at,first_seen_at,last_seen_at,signal_value,category,score) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source,external_id) DO UPDATE SET title=excluded.title,url=excluded.url,published_at=excluded.published_at,last_seen_at=excluded.last_seen_at,signal_value=excluded.signal_value,category=excluded.category,score=excluded.score").bind(x.source,x.external_id,x.title,x.url,x.published_at,t,t,x.signal_value,x.category,s).run();}
async function runOnce(env){const started=now(),rr=await Promise.allSettled([readGoogleTrends(),readHackerNews()]),signals=rr.flatMap(r=>r.status==="fulfilled"?r.value:[]),errors=rr.filter(r=>r.status==="rejected").map(r=>String(r.reason));for(const x of signals)await upsert(env,x);await env.DB.prepare("INSERT INTO runs(started_at,finished_at,status,source_count,signal_count,error) VALUES(?,?,?,?,?,?)").bind(started,now(),errors.length?"partial":"ok",2,signals.length,errors.join(" | ")||null).run();return {ok:true,signals:signals.length,errors};}
export default {async fetch(request,env){const u=new URL(request.url);if(request.method==="GET"&&u.pathname==="/")return new Response(JSON.stringify({service:"trend-radar",mode:"signal-collection",publishing_enabled:false,ai_enabled:false}),{headers:JSON_HEADERS});if(request.method==="GET"&&u.pathname==="/health"){let db="ok";try{await env.DB.prepare("SELECT 1").first();}catch(_){db="error";}return new Response(JSON.stringify({ok:db==="ok",db}),{headers:JSON_HEADERS});}if(request.method==="POST"&&u.pathname==="/run"){try{return new Response(JSON.stringify(await runOnce(env)),{headers:JSON_HEADERS});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e)}),{status:500,headers:JSON_HEADERS});}}return new Response(JSON.stringify({error:"not_found"}),{status:404,headers:JSON_HEADERS});},async scheduled(_controller,env,ctx){ctx.waitUntil(runOnce(env));}};
